language: php
# Taken from OVH
# https://www.ovh.nl/shared-hosting/persoonlijke-shared-hosting.xml
# and https://github.com/splitbrain/dokuwiki-travis
php:
    #  - "7.4"
    #  - "7.3"
    #  - "7.2"
    #  - "7.1"
    #  - "7.0"
    - "5.6"

env:
    - DOKUWIKI=stable

before_script:
    - "curl -H 'Authorization: token ${TOKEN}' -o boot.sh https://raw.githubusercontent.com/ComboStrap/combo_dev/master/ci/boot.sh"
    - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
    - bash boot.sh
    - sh travis.sh

script:
    - cd _test && ./phpunit.phar --stderr --group plugin_combo --verbose --debug

notifications:
    email:
        - support@combostrap.com
