language: php
# Taken from OVH
# https://www.ovh.nl/shared-hosting/persoonlijke-shared-hosting.xml
# and https://github.com/splitbrain/dokuwiki-travis
php:
    - "7.4" - Array and string offset access syntax with curly braces is deprecated vendor/marcusschwarz/lesserphp/lessc.inc.php:761
    - "7.3"
    - "7.2"
    - "7.1"
    - "7.0"
    - "5.6"

env:
    - DOKUWIKI=stable

before_script:
    # - set | grep TRAVIS
    - "curl -H \"Authorization: token ${TOKEN}\" -o \"boot.sh\" \"https://raw.githubusercontent.com/ComboStrap/combo_test/${TRAVIS_BRANCH}/resources/script/ci/boot.sh\""
    - bash boot.sh

script:
    - cd _test && ./phpunit.phar --stderr --group plugin_combo --verbose --debug

branches:
    only:
        - master
        - stable

notifications:
    email:
        - support@combostrap.com
