# General doc
# https://www.ovh.nl/shared-hosting/persoonlijke-shared-hosting.xml
# and https://github.com/splitbrain/dokuwiki-travis
# and https://www.dokuwiki.org/devel:release_process

branches:
    only:
        - main
        - stable

# https://docs.travis-ci.com/user/build-matrix/#excluding-jobs-with-env-value
jobs:
    include:
        ## not "7.4" because Array and string offset access syntax with curly braces is deprecated vendor/marcusschwarz/lesserphp/lessc.inc.php:761
        -   language: php
            php: "7.3"
            env: DOKUWIKI=stable # the last version of dokuwiki (master = dev, old-stable = previous)
        -   language: php
            php: "5.6"
            env: DOKUWIKI=stable # the last version of dokuwiki (master = dev, old-stable = previous)
            # https://config.travis-ci.com/ref/job/if/condition
        -   if: branch =~ ^main
            language: php
            env: DOKUWIKI=stable # the last version of dokuwiki (master = dev, old-stable = previous)
            php: "7.2"
        -   if: branch =~ ^main
            language: php
            php: "7.1"
            env: DOKUWIKI=stable # the last version of dokuwiki (master = dev, old-stable = previous)
        -   if: branch =~ ^main
            language: php
            php: "7.0"
            env: DOKUWIKI=stable # the last version of dokuwiki (master = dev, old-stable = previous)


before_script:
    # - set | grep TRAVIS
    - "curl -H \"Authorization: token ${TOKEN}\" -o \"boot.sh\" \"https://raw.githubusercontent.com/ComboStrap/combo_test/${TRAVIS_PULL_REQUEST_BRANCH}/resources/script/ci/boot.sh\""
    - bash boot.sh

script:
    - cd _test && ./phpunit.phar --stderr --group plugin_combo --verbose --debug

notifications:
    email:
        - support@combostrap.com

