<?php


namespace ComboStrap;

/**
 * A Document that is generated by the page compiler
 * @package ComboStrap
 * Represent a compiled document.
 */
abstract class PageCompilerDocument implements CachedDocument
{

    /**
     * @var Page
     */
    protected $page;

    /**
     * @var string|null
     */
    protected $content;

    /**
     * Document constructor.
     * @param Page $page
     */
    public function __construct(Page $page)
    {
        $this->page = $page;
    }


    /**
     * @return Page
     */
    function getPage(): Page
    {
        return $this->page;
    }

    /**
     * @return string - the last part name of the renderer file without the php extension
     * known inside dokuwiki as the mode
     *
     * For instance for the renderer
     * renderer_plugin_combo_analytics
     * the name is
     * combo_analytics
     */
    abstract function getRendererName(): string;

    /**
     * Get the data from the cache file
     * or compile the content
     *
     * @return array|string - array ({@link InstructionsDocument)) or string
     * @throws ExceptionNotFound
     */
    public function getOrProcessContent()
    {

        if ($this->shouldProcess()) {

            /**
             * Cache Miss
             */
            $this->process();

        }

        return $this->getContent();


    }

    /**
     * @return array|string
     * @throws ExceptionNotFound - if the file was not found
     */
    public function getContent()
    {

        if ($this->content !== null) {
            return $this->content;
        } else {
            return $this->getFileContent();
        }

    }


    /**
     *
     * @return array|string a string (default) or an array {@link InstructionsDocument::getFileContent()}
     * @throws ExceptionNotFound
     */
    public function getFileContent()
    {

        return FileSystems::getContent($this->getCachePath());

    }


    /**
     * @param $content
     * @return mixed
     */
    protected function setContent($content)
    {
        $this->content = $content;
        $this->storeContent($content);
        return $this;
    }

    /**
     * @return array
     */
    function getDepends(): array
    {
        $depends = [];
        foreach ($this->getPage()->getChildren() as $child) {
            $depends['files'][] = $child->getPath()->toLocalPath()->toString();
        }
        return $depends;
    }

}
