<?php


namespace ComboStrap;

/**
 * A Document that is generated by the page compiler
 * @package ComboStrap
 * Represent a compiled document.
 */
abstract class PageCompilerDocument implements CachedDocument
{

    /**
     * @var Page
     */
    private $page;

    /**
     * Document constructor.
     * @param Page $page
     */
    public function __construct(Page $page)
    {
        $this->page = $page;
    }


    function getPage(): Page
    {
        return $this->page;
    }

    /**
     * @return string - the last part name of the renderer file without the php extension
     * known inside dokuwiki as the mode
     *
     * For instance for the renderer
     * renderer_plugin_combo_analytics
     * the name is
     * combo_analytics
     */
    abstract function getRendererName(): string;

    /**
     * Get the data from the cache file
     * or compile the content
     *
     * @return false|mixed|string
     */
    public function getOrProcessContent()
    {
        if ($this->shouldProcess()) {

            /**
             * Cache Miss
             */
            return $this->process();

        } else {

            $content = $this->getFileContent();

            /**
             * Cache hit
             */
            if (
                (Site::debugIsOn() || PluginUtility::isDevOrTest())
                && $this->getExtension() === HtmlDocument::extension
            ) {
                $logicalId = $this->getPage()->getLogicalId();
                $scope = $this->getPage()->getScope();
                $content = "<div id=\"{$this->getPage()->getCacheHtmlId()}\" style=\"display:none;\" data-logical-Id=\"$logicalId\" data-scope=\"$scope\" data-cache-op=\"hit\" data-cache-file=\"{$this->getCachePath()->toString()}\"></div>" . $content;
            }
            return $content;
        }


    }

    /**
     *
     * @return null|mixed the content of the file (by default in a text format)
     * @noinspection PhpReturnDocTypeMismatchInspection
     */
    public function getFileContent()
    {
        if (!FileSystems::exists($this->getCachePath())) {
            return null;
        }
        return FileSystems::getContent($this->getCachePath());
    }


    public function deleteIfExists(): PageCompilerDocument
    {
        FileSystems::deleteIfExists($this->getCachePath());
        return $this;
    }

}
