<?php


namespace ComboStrap;

/**
 * A Document that is generated by the page compiler
 * @package ComboStrap
 * Represent a compiled document.
 */
abstract class PageCompilerDocument implements CachedDocument
{

    /**
     * @var Page
     */
    protected $page;

    /**
     * @var string|null
     */
    protected $content;

    /**
     * Document constructor.
     * @param Page $page
     */
    public function __construct(Page $page)
    {
        $this->page = $page;
    }


    /**
     * @return Page
     */
    function getPage(): Page
    {
        return $this->page;
    }

    /**
     * @return string - the last part name of the renderer file without the php extension
     * known inside dokuwiki as the mode
     *
     * For instance for the renderer
     * renderer_plugin_combo_analytics
     * the name is
     * combo_analytics
     */
    abstract function getRendererName(): string;

    /**
     * Get the data from the cache file
     * or compile the content
     *
     * @return mixed - array ({@link InstructionsDocument)) or string
     */
    public function getOrProcessContent()
    {

        if ($this->shouldProcess()) {

            /**
             * Cache Miss
             */
            $this->process();

        }

        return $this->getContent();


    }

    /**
     * @return array|string|null
     */
    public function getContent()
    {

        if ($this->content !== null) {
            return $this->content;
        } else {
            return $this->getFileContent();
        }

    }


    /**
     *
     * @return null|mixed the content of the file (by default in a text format)
     */
    public function getFileContent()
    {
        if (!FileSystems::exists($this->getCachePath())) {
            return null;
        }
        return FileSystems::getContent($this->getCachePath());
    }



    /**
     * @param $content
     * @return mixed
     */
    protected function setContent($content)
    {
        $this->content = $content;
        $this->storeContent($content);
        return $this;
    }


}
