alter table PAGES add column REGION TEXT;
update PAGES set REGION = COUNTRY;
update pages set COUNTRY = null;

ALTER TABLE PAGES_ALIAS RENAME TO DEPRECATED_PAGES_ALIAS;
DROP INDEX PAGES_ALIAS_UK;
CREATE INDEX DEPRECATED_PAGES_ALIAS_UK ON DEPRECATED_PAGES_ALIAS (ALIAS);


CREATE TABLE PAGE_ALIASES
(
    UUID TEXT,  -- The uuid
    ALIAS TEXT   -- The alias value
);

CREATE UNIQUE INDEX PAGE_ALIAS_UK ON PAGE_ALIASES (UUID, ALIAS);
