# https://docs.github.com/en/actions/learn-github-actions/contexts
name: Example Env

on:
  # Manually running a workflow from the UI
  # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually
  # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
  workflow_dispatch:
    inputs:
      versions:
        description: 'Version of the interpreter'
        required: true
        default: "['7.4','8.2']"
        # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype
        type: choice
        options:
          - "['7.4','8.2']"
          - "['8.2']"
          - "['7.4']"


permissions: # Setting permissions for the token
  contents: read # needed to fetch code

# A list of the jobs that run in the workflow file.
jobs:
  env-demo: # The identifier of the job

    name: Test on php ${{ matrix.php-versions }} # The name of the job

    runs-on: ubuntu-latest

    strategy:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        # 2 jobs will run, one for each include entry
        # because we don't specify any matrix variables
        # All configurations under include will run
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-adding-configurations
        version: ${{ fromJson(inputs.versions) }}
      fail-fast: false


    env:
      LITERAL_STRING_ENV: lib/plugins/combo
      LITERAL_ARRAY_ENV: ${{ fromJSON('{"7.4":"Dependency Variable for 7.4","8.2":"Dependency Variable for 8.2"}') }}
      DEPENDENCY_VIA_COMMAND: "${{ matrix.version == '7.4' && '7.4 version' || 'not 7.4 version' }}"
      DEPENDENCY_VIA_ARRAY: ${{ jobs.env.LITERAL_ARRAY_ENV[matrix.version] }}

    steps:

      # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump Input context
        run: echo '${{ toJSON(inputs) }}'

      - name: Echo manual env
        run: |
          echo ("$LITERAL_STRING_ENV");
          echo ("$LITERAL_ARRAY_ENV");
          echo ("$DEPENDENCY_VIA_COMMAND");
          echo ("$DEPENDENCY_VIA_ARRAY");
