name: PHP Tests started on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-test-workflow:
    uses: ./.github/workflows/php-test-reusable.yml
    secrets: inherit
    with:
      versions: "['8.2']"
