name: PHP Test

on:
  workflow_dispatch: # Manually running a workflow from the UI
  pull_request:
    branches: [ "main" ]

permissions: # Setting permissions for the token
  contents: read # needed to fetch code

# A list of the jobs that run in the workflow file.
jobs:
  test: # The identifier of the job

    name: Test on php ${{ matrix.php-versions }} # The name of the job

    runs-on: ubuntu-latest

    strategy:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        php-versions: [ '7.4', '8.2' ]
      fail-fast: false

    steps:

      # https://github.com/marketplace/actions/setup-php-action#matrix-setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, PDO, pdo_sqlite, pdo_mysql, pdo_pgsql, bz2
          ini-values: pcre.jit=0

      # Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      # Cloning your repository to the runner
      - uses: actions/checkout@v3

      # Runs command-line programs using the operating system's shell.
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      - name: Php Bootstrap (Preconfiguration)
        run: |
          chmod +x .github/bootstrap.sh
          source .github/bootstrap.sh
        # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DOKUWIKI: 'master' # the branch where we test
        working-directory: .
        shell: bash

      # with verbose, you see the configuration file used at the beginning
      - name: Test
        run: |
          cd _test && ./phpunit.phar --stderr --group plugin_combo --verbose --debug
