DROP TABLE page_references;

CREATE TABLE PAGE_REFERENCES
(
    PAGE_ID TEXT,
    REFERENCE TEXT
);

CREATE UNIQUE INDEX PAGE_REFERENCES_IDX ON PAGE_REFERENCES (PAGE_ID,REFERENCE);
CREATE INDEX PAGE_REFERENCES_IDX_SOURCE ON PAGE_REFERENCES (PAGE_ID);
CREATE INDEX PAGE_REFERENCES_IDX_TARGET ON PAGE_REFERENCES (REFERENCE);
